EXPLANATIONS: dict[str, str] = {
    "BVM001": "A required BVM path is missing or has the wrong file type.",
    "BVM002": "vault.toml is missing required fields or cannot be parsed.",
    "BVM003": "INDEX.json is malformed or missing required index fields.",
    "BVM004": "vault.toml contains a key the specification does not define.",
    "BVM010": "Managed Markdown lacks valid strict-JSON BVM metadata.",
    "BVM011": "Two artifacts use the same artifact_id.",
    "BVM012": "An artifact metadata state is unknown.",
    "BVM013": "Artifact state does not match its managed directory.",
    "BVM014": "Artifact version is not semantic versioning syntax.",
    "BVM015": "A durable timestamp is invalid or temporally inconsistent.",
    "BVM016": "A vault reference is unsafe, missing, or leaves the vault.",
    "BVM017": "Artifact metadata is missing a required field or has the wrong type.",
    "BVM018": "An artifact contains duplicate evidence or review references.",
    "BVM020": "A receipt JSON file is malformed, ambiguous, or uses an unsupported schema.",
    "BVM021": "An evidence receipt source or executed object is missing or unsafe.",
    "BVM022": "A declared source or object SHA-256 does not match the referenced bytes.",
    "BVM023": "An artifact cites a receipt that has been explicitly superseded.",
    "BVM024": "Active receipts for one canonical subject and applicability boundary contradict without explicit supersession.",
    "BVM025": "Receipt identity, subject, kind, status, timestamp, or required field is invalid.",
    "BVM026": "Receipt supersession or review chronology is inconsistent with the claimed transition.",
    "BVM030": "A canon artifact lacks evidence receipts.",
    "BVM031": "A canon artifact lacks a qualifying non-self review receipt.",
    "BVM032": "A canon artifact lacks a promotion receipt.",
    "BVM033": "A promotion receipt does not match the exact artifact, frozen candidate, or gate inputs.",
    "BVM034": "A canon artifact is not reachable as current from INDEX.json.",
    "BVM035": "More than one live canon artifact exists for one lineage.",
    "BVM036": "A promotion or index timestamp predates one of its required inputs.",
    "BVM037": "A review receipt is not bound to the exact reviewed artifact bytes.",
    "BVM040": "A supersession target is missing or belongs to a different lineage.",
    "BVM041": "The supersession graph contains a cycle.",
    "BVM042": "A superseding artifact does not have a greater semantic version.",
    "BVM043": "A current canon artifact's predecessor is not preserved in ARCHIVE.",
    "BVM044": "An archived artifact is orphaned from supersession and retraction history.",
    "BVM050": "A retraction record is malformed or incomplete.",
    "BVM051": "A retraction does not preserve or hash-identify the archived original.",
    "BVM052": "A retraction replacement is invalid, unbound, or outside current CANON.",
    "BVM053": "A retraction timestamp predates the archived artifact or declared replacement state.",
    "BVM060": "A negative result lacks a positive-control receipt in its evidence set.",
    "BVM061": "The cited positive-control receipt is not a passing positive control.",
    "BVM062": "An aggregate claim has an invalid or incomplete unit declaration.",
    "BVM063": "An aggregate unit lacks a matching passing unit-check receipt.",
    "BVM064": "A negative-existence claim lacks an authoritative-search receipt.",
    "BVM065": "The cited authoritative-search receipt lacks the required authority, procedure, or boundary.",
    "BVM070": "A canonical-object-dependent claim lacks an executed-object receipt in its evidence set.",
    "BVM071": "The cited canonical-object receipt is not a passing, hash-bound executed-object receipt.",
    "BVM072": "A proxy is attempting to inherit a claim about the canonical object.",
    "BVM080": "An index entry does not resolve to matching canon state.",
    "BVM081": "An index entry's lineage or version disagrees with the artifact.",
    "BVM082": "An index entry does not bind the current promotion receipt by path and SHA-256.",
    "BVM090": "A managed handoff omits required continuity sections or durable authority references.",
}
